# -*- coding: utf-8 -*-
"""Blackboard25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18w4v2XgHuzsXDVqyI4VLTLM_9iaRNIFK

1. Write a Python class to reverse a string word by word.

Example:
Input string : 'hello .py'
Expected Output : '.py hello'
"""

class StringReverser:
    def __init__(self, input_string):
        self.input_string = input_string

    def reverse_words(self):
        words = self.input_string.split()
        reversed_string = ' '.join(reversed(words))
        return reversed_string

# Example usage:
input_str = 'hello .py'
reverser = StringReverser(input_str)

result = reverser.reverse_words()
print(f"Input string: '{input_str}'")
print(f"Reversed string: '{result}'")

"""2. Write a Python class named Circle constructed by a radius and two methods which will compute the area and the perimeter of a circle.

"""

class Circle:
    def __init__(self, radius):
        self.radius = radius

    def compute_area(self):
        area = 3.14 * (self.radius ** 2)
        return area

    def compute_perimeter(self):
        perimeter = 2 * 3.14 * self.radius
        return perimeter

# Example usage:
radius_value = 5
circle_instance = Circle(radius_value)

area_result = circle_instance.compute_area()
perimeter_result = circle_instance.compute_perimeter()

print(f"Circle with radius {radius_value}:")
print(f"Area: {area_result}")
print(f"Perimeter: {perimeter_result}")